### ISSUE TITLE
feature request: aliases or something, for more manageable account channel names

### ISSUE THREAD

**Issue by shmibs** [kensanata/bitlbee-mastodon#10]
the length of a "#\<instance\>_\<username\>" channel name is pretty unwieldy / eats space (see attached screenshot).

it would be nice to have some means for the user to rename these channels (possibly through something like user-defined aliases for accounts? or just setting a channel name directly?) 

or am i missing something obvious?

![2018-1516681471](https://user-images.githubusercontent.com/2358713/35258425-975da0ce-ffbc-11e7-9ee9-39f57c5e88ef.png)

**Comment by kensanata** [comment]
Hm, it never bothered me because my client looks different, I guess. All I know is that bitlbee allows you to rename the account, so you could shorten the resulting channel name.

**Comment by kensanata** [comment]
I'm not sure what to do with this issue. There doesn't seem to be much to do for me. If at all, it's probably up to Bitlbee itself?

**Comment by shmibs** [comment]
well, the reason i asked in the firstplace was because other plugins seem to have this sort of functionality. the [discord](https://github.com/sm00th/bitlbee-discord/) plugin has a built-in method for assigning remote channels to irc channels with user-defined names rather than just generating the names automatically, and the google talk plugin has options for different nick-assignment formats, with some longer options. perhaps there could be something like an optional nick-format setting? so, rather than including the full-length nick, it's truncated to only that length necessary for unique identification among whatever set.

sorry for being so vague and non-helpful, though; should really look more into how bitlbee works X_X

**Comment by kensanata** [comment]
Hm, I'm not sure this is actually a "feature" of bitlbee-discord. I assume you are talking about the following process: first, you list the available channels on the Discord server. They all have a number. Now you need to tell the plugin which ones you are actually interested in so what you do is you create a mapping between Bitlbee channel names and Discord channel names, and then you join those Bitlbee channels. When I first saw that, I felt it was super cumbersome and wanted all the channels to be defined for me. Only later did I suspect that some Discord server simply have so many channels that this turns out to be impracticable.
I just went back and looked at how hashtag subscription works. Those channels are simple enough: you can rename them however you want and all that matters is that their topic matches the hashtag in question.
Hm...
OK, I looked at the code again and I have a suggestion: try the develop branch https://github.com/kensanata/bitlbee-mastodon/tree/develop and restart Bitlbee. Then take the account offline, use the new name setting and put it online again:
```
account mastodon off
account mastodon set name masto
account on
save
```
Does that do what you want?

**Comment by shmibs** [comment]
that really helps, yeh, thank you so much ^_^

![2018-1518294200](https://user-images.githubusercontent.com/2358713/36066382-abe3e88e-0e65-11e8-9326-c0e5e2797420.png)

**Comment by kensanata** [comment]
Excellent. I added some documentation and merged it into the master branch.
